packages:
    - name: scrape
      functions:
        - name: get_menu
          runtime: python:default
          web: false
          environment:
            DB_NAME: "${_self.DATABASE}"
            DB_PASSWORD: "${self_.PASSWORD}"
            DB_USER: "${_self.USERNAME}"
            DB_HOST: "${_self.HOSTNAME}"
            DB_PORT: "${_self.PORT}"
            DB_URL: "${_self.DATABASE_URL}"
          limits:
            timeout: 30000
            memory: 512


