packages:
    - name: scrape
      functions:
        - name: get_menu
          runtime: python:default
          web: true
          environment:
            DATABASE_URL: "${DATABASE_URL}"
          limits:
            timeout: 60000
            memory: 512


