packages:
    - name: scrape
      functions:
        - name: get_menu
          runtime: python:default
          web: false
          environment:
          limits:
            timeout: 30000
            memory: 512


