packages:
    - name: scrape
      functions:
        - name: get_menu
          runtime: python:default
          web: false
          environment:
            DB_NAME: "${DB_NAME}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_USER: "${DB_USER}"
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT}"
            DB_URL: "${DB_URL}"
          limits:
            timeout: 30000
            memory: 512


